name: STM32 Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make openjdk-17-jre

      - name: Build
        run: |
          ./STM32CubeIDE \
          --launcher.suppressErrors \
          -nosplash \
          -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
          -data workspace \
          -importAll . \
          -build all
